### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [alevy/simple#26]
```
simple-templates               > /tmp/stack-12dc90534892fb49/simple-templates-1.0.0/src/Web/Simple/Templates/Language.hs:71:57: error:
simple-templates               >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
simple-templates               >                      with: H.HashMap Identifier Value
simple-templates               >       Expected: H.HashMap Identifier Value
simple-templates               >         Actual: Object
simple-templates               >     • In the second argument of ‘H.lookup’, namely ‘obj’
simple-templates               >       In the second argument of ‘($)’, namely ‘H.lookup ident obj’
simple-templates               >       In the expression: fromMaybe Null $ H.lookup ident obj
simple-templates               >    |
simple-templates               > 71 |           Object obj -> fromMaybe Null $ H.lookup ident obj
simple-templates               >    |                                                         ^^^
simple-templates               > 
simple-templates               > /tmp/stack-12dc90534892fb49/simple-templates-1.0.0/src/Web/Simple/Templates/Language.hs:77:57: error:
simple-templates               >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
simple-templates               >                      with: H.HashMap Identifier Value
simple-templates               >       Expected: H.HashMap Identifier Value
simple-templates               >         Actual: Object
simple-templates               >     • In the second argument of ‘H.lookup’, namely ‘obj’
simple-templates               >       In the second argument of ‘($)’, namely ‘H.lookup ident obj’
simple-templates               >       In the expression: fromMaybe Null $ H.lookup ident obj
simple-templates               >    |
simple-templates               > 77 |           Object obj -> fromMaybe Null $ H.lookup ident obj
simple-templates               >    |                                                         ^^^
simple-templates               > 
simple-templates               > /tmp/stack-12dc90534892fb49/simple-templates-1.0.0/src/Web/Simple/Templates/Language.hs:101:41: error:
simple-templates               >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
simple-templates               >                      with: H.HashMap a0 Value
simple-templates               >       Expected: H.HashMap a0 Value
simple-templates               >         Actual: Object
simple-templates               >     • In the first argument of ‘H.toList’, namely ‘obj’
simple-templates               >       In the first argument of ‘go’, namely ‘(H.toList obj)’
simple-templates               >       In the second argument of ‘($)’, namely ‘go (H.toList obj) mempty’
simple-templates               >     |
simple-templates               > 101 |     Object obj -> String $ go (H.toList obj) mempty
simple-templates               >     |                                         ^^^
simple-templates               > 
simple-templates               > /tmp/stack-12dc90534892fb49/simple-templates-1.0.0/src/Web/Simple/Templates/Language.hs:121:52: error:
simple-templates               >     • Couldn't match type: H.HashMap Identifier Value
simple-templates               >                      with: Data.Aeson.KeyMap.KeyMap Value
simple-templates               >       Expected: Object
simple-templates               >         Actual: H.HashMap Identifier Value
simple-templates               >     • In the second argument of ‘($)’, namely
simple-templates               >         ‘H.insert varName newVal orig’
simple-templates               >       In the expression: Object $ H.insert varName newVal orig
simple-templates               >       In an equation for ‘replaceVar’:
simple-templates               >           replaceVar (Object orig) varName newVal
simple-templates               >             = Object $ H.insert varName newVal orig
simple-templates               >     |
simple-templates               > 121 | replaceVar (Object orig) varName newVal = Object $ H.insert varName newVal orig
simple-templates               >     |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simple-templates               > 
simple-templates               > /tmp/stack-12dc90534892fb49/simple-templates-1.0.0/src/Web/Simple/Templates/Language.hs:121:76: error:
simple-templates               >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
simple-templates               >                      with: H.HashMap Identifier Value
simple-templates               >       Expected: H.HashMap Identifier Value
simple-templates               >         Actual: Object
simple-templates               >     • In the third argument of ‘H.insert’, namely ‘orig’
simple-templates               >       In the second argument of ‘($)’, namely
simple-templates               >         ‘H.insert varName newVal orig’
simple-templates               >       In the expression: Object $ H.insert varName newVal orig
simple-templates               >     |
simple-templates               > 121 | replaceVar (Object orig) varName newVal = Object $ H.insert varName newVal orig
simple-templates               >     |                                                                            ^^^^
simple-templates               > 
simple-templates               > /tmp/stack-12dc90534892fb49/simple-templates-1.0.0/src/Web/Simple/Templates/Language.hs:122:39: error:
simple-templates               >     • Couldn't match type ‘Text’ with ‘Key’
simple-templates               >       Expected: Key
simple-templates               >         Actual: Identifier
simple-templates               >     • In the first argument of ‘(.=)’, namely ‘varName’
simple-templates               >       In the expression: varName .= newVal
simple-templates               >       In the first argument of ‘object’, namely ‘[varName .= newVal]’
simple-templates               >     |
simple-templates               > 122 | replaceVar _ varName newVal = object [varName .= newVal]
simple-templates               >     |                                       ^^^^^^^
```

**Comment by alaendle** [comment]
Guess this can be closed? https://hackage.haskell.org/package/simple-2.0.0/reports/1 indicates this project builds with newer aeson versions.
